#!/bin/bash

OPTIONS=""

while getopts "S" opt; do
    case $opt in
        S)
            OPTIONS="-S"
            shift
            ;;
    esac
done

rm -rf deb.*
rm -rf *.tar.gz

qmake && make dist

for DIST in $*; do
    mkdir deb.$DIST
    cp *.tar.gz deb.$DIST

    pushd deb.$DIST

    PACKAGE=`ls *.tar.gz | grep -Po '^[A-Za-z-]+'`
    DEBPACKAGE=`echo $PACKAGE | sed -r 's/([A-Z])/-\1/g' | tr '[:upper:]' '[:lower:]'`
    VERSION=`ls *.tar.gz | grep -Po '[0-9]+\.[0-9]+\.[0-9]+'`
    mv ${PACKAGE}${VERSION}.tar.gz ${DEBPACKAGE}_${VERSION}.orig.tar.gz
    tar -xzf ${DEBPACKAGE}_${VERSION}.orig.tar.gz
    mv ${PACKAGE}${VERSION} ${DEBPACKAGE}-${VERSION}
    pushd ${DEBPACKAGE}-${VERSION}
    cp -r ../../debian.$DIST ./debian

    debuild $OPTIONS -sa -uc -us -rfakeroot

    popd

    popd
done
